# Generated by Django 2.2.2 on 2024-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('fazendo', 'Fazendo'), ('finalizado', 'Finalizado')], max_length=1),
        ),
    ]
